### ISSUE TITLE
Where is the getting started on Linux?

### ISSUE THREAD

**Issue by bus710** [intel/rsp-sw-toolkit-installer#7]
Thanks for this repo to share the information regarding RSP.

I was hoping to find the guide for Linux in the [link](https://software.intel.com/en-us/getting-started-with-intel-rfid-sensor-platform-on-linux) on the README.md of this repo but I am getting redirected to [the portal](https://software.intel.com/content/www/us/en/develop/home.html). This is not only issue of the README.md but every RSP page has wrong link so that I guess the portal page's recent renewal missed the right link.

I wonder if one of [the documents](https://github.com/intel/rsp-sw-toolkit-gw/tree/master/docs) is the actual contents.

**Comment by tim-shockley** [comment]
It appears that the web site hosting the getting started guide was upgraded and unfortunately the content has seeminly disappeared from that site. I searched on the portal but have been unable to locate the getting started guide. We are working the issue and will post back when it has been resolved.

**Comment by bus710** [comment]
@tim-shockley, 

Thanks for your quick response!
I will be looking forward for the getting started.

**Comment by tim-shockley** [comment]
Basically, clone this repo and run either the native or docker build.sh script. Look in that file to see what is going on.
It clones https://github.com/intel/rsp-sw-toolkit-gw (the RSP Controller repo), builds it, starts it, and opens a web browser.
After the controller is up and running, look at the examples in that repo
https://github.com/intel/rsp-sw-toolkit-gw/tree/master/examples/use-cases

**Comment by bus710** [comment]
I guess anyone wants to find out what need to be done to setup the RSP controller can refer @tim-shockley's comment and that might be the contents of the missing link. Let me close this.

Thanks,
